### ISSUE TITLE
Link to you build it you run it playbook

### ISSUE THREAD

**Issue by bethantimmins** [EqualExperts/digital-platform-playbook#10]
Is it possible in this section https://digital-platform.playbook.ee/practices/paved-road#enable-you-build-it-you-run-it to add a link to the You Build It You Run it Playbook to encourage cross-sharing between playbooks?

The URL is https://you-build-it-you-run-it.playbook.ee/

**Comment by AdamHansrod** [comment]
Sure, have you got any specific link text/sentence in mind?

**Comment by AdamHansrod** [comment]
PR with proposed text changes
https://github.com/EqualExperts/digital-platform-playbook/pull/11
